baseurl = "http://bethqiang.com/"
title = "Beth Qiang"
languageCode = "en-us"
disqusShortname = "bethqiang"
googleAnalytics = "UA-85574806-1"

# Number of posts per page
paginate = 10

[blackfriday]
  hrefTargetBlank = true

[params]
  viewMorePostLink = "/blog/"
  author = "Beth Qiang"
  description = "A developer's thoughts on life, code, and the pursuit of happiness."

  # Social
  twitter = "bethqiang"
  linkedin = "bethqiang08"
  github = "bethqiang"
  email = "beth@bethqiang.com"

  # Format dates with Go's time formatting
  date_format = "January 2, 2006"

[Permalinks]
  blog = "/blog/:year/:month/:day/:filename/"

[[params.menu]]
  name = "Home"
  url  = "/"
  weight = 1

[[params.menu]]
  name = "About"
  url  = "/about/"
  weight = 2

[[params.menu]]
  name = "Blog"
  url  = "/blog/"
  weight = 3

# Widgets for the right sidebar
[params.widgets]
  categories = true
  tags = true
  search = true

[params.recent_posts]
  enable = true
  title = "From the Blog"
